codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "70...95"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
ignore:
  - "test_files/"
  - "srcs/db/*"
  - "subprojects/**/*"
  - "cli.c"
  - "srcs/ospl.c"