dist: bionic
group: travis_latest
os: linux
language: c
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"
install:
  - pip3 install meson ninja
before_install:
  - sudo apt-get install -y libmagic-dev libjpeg-dev libexif-dev libsqlite3-dev lcov 
matrix:
  include:
    - env: CC=gcc
    - env: CC=clang
script:
  - meson builddir -Db_coverage=true
  - meson compile -C builddir
  - chmod +x scripts/create_emptyfiles.sh
  - meson compile empty_files -C builddir
  - meson test -C builddir --print-errorlogs
  - ninja -C builddir coverage
after_success:
  - bash <(curl -s https://codecov.io/bash) -v